DROP DOMAIN IF EXISTS record_id_type;
DROP DOMAIN IF EXISTS service_provider_id_type;
DROP DOMAIN IF EXISTS ref_type_type;
DROP DOMAIN IF EXISTS ref_code_type;
DROP DOMAIN IF EXISTS ref_desc_type;
DROP DOMAIN IF EXISTS user_name_type;
DROP DOMAIN IF EXISTS email_id_type;
DROP DOMAIN IF EXISTS aadhar_number_type;
DROP DOMAIN IF EXISTS pan_type;
DROP DOMAIN IF EXISTS tan_id_type;
DROP DOMAIN IF EXISTS voter_id_type;
DROP DOMAIN IF EXISTS address_line_type;
DROP DOMAIN IF EXISTS zip_code_type;
DROP DOMAIN IF EXISTS org_id_type;
DROP DOMAIN IF EXISTS org_name_type;
DROP DOMAIN IF EXISTS cell_number_type;
DROP DOMAIN IF EXISTS pin_code_type;
DROP DOMAIN IF EXISTS partner_relationship_type_type;
DROP DOMAIN IF EXISTS pw_state_type;
DROP DOMAIN IF EXISTS version_num_type;
DROP DOMAIN IF EXISTS msg_id_type;
DROP DOMAIN IF EXISTS msg_status_type;
DROP DOMAIN IF EXISTS attachment_name_type;
DROP DOMAIN IF EXISTS encoding_format_type;
DROP DOMAIN IF EXISTS user_principal_type;
DROP DOMAIN IF EXISTS user_type_type;
DROP DOMAIN IF EXISTS system_user_type_type;
DROP DOMAIN IF EXISTS license_id_type;
DROP DOMAIN IF EXISTS id_type;
DROP DOMAIN IF EXISTS otp_type;
DROP DOMAIN IF EXISTS tax_identity_type_type;
DROP DOMAIN IF EXISTS tax_identifier_type;
DROP DOMAIN IF EXISTS order_num_type;
DROP DOMAIN IF EXISTS address_id_type;
DROP DOMAIN IF EXISTS item_id_type;
DROP DOMAIN IF EXISTS general_string_type;
DROP DOMAIN IF EXISTS num_type;
DROP DOMAIN IF EXISTS order_id_type;
DROP DOMAIN IF EXISTS description_type;
DROP DOMAIN IF EXISTS amount_type;
DROP DOMAIN IF EXISTS notes_type;
DROP DOMAIN IF EXISTS quantity_type;
DROP DOMAIN IF EXISTS msg_type_name_type;

DROP DOMAIN IF EXISTS acct_identifier_type;
DROP DOMAIN IF EXISTS acct_name_type;
DROP DOMAIN IF EXISTS acct_number_type;



CREATE DOMAIN record_id_type bigint;
CREATE DOMAIN service_provider_id_type varchar(10);
CREATE DOMAIN zip_code_type varchar(6);
CREATE DOMAIN ref_type_type varchar(5) CONSTRAINT ref_code_type_values CHECK (VALUE IN ('00001', '00002', '00003', '00004','00005','00006','00007','00008','00009'));
CREATE DOMAIN ref_code_type varchar(10);
CREATE DOMAIN ref_desc_type varchar(100);
CREATE DOMAIN user_name_type varchar(256);
CREATE DOMAIN email_id_type varchar(320);
CREATE DOMAIN aadhar_number_type char(12);
CREATE DOMAIN pan_type char(10);
CREATE DOMAIN tan_id_type char(10);
CREATE DOMAIN voter_id_type char(10);
CREATE DOMAIN address_line_type varchar(256);
CREATE DOMAIN org_id_type varchar(10);
CREATE DOMAIN org_name_type varchar(100);
CREATE DOMAIN cell_number_type varchar(20);
CREATE DOMAIN pin_code_type varchar(6);
CREATE DOMAIN partner_relationship_type_type char(1) CONSTRAINT partner_relationship_type_type_values CHECK (VALUE IN('S', 'D',    'B'));
CREATE DOMAIN pw_state_type  char(1) CONSTRAINT pw_state_type_type CHECK (VALUE IN ('N', 'F', 'S'));
CREATE DOMAIN version_num_type bigint;
CREATE DOMAIN msg_id_type varchar(20);
CREATE DOMAIN msg_status_type char(1);
CREATE DOMAIN attachment_name_type varchar(100);
CREATE DOMAIN encoding_format_type char(1);
CREATE DOMAIN user_principal_type varchar(30);
CREATE DOMAIN user_type_type  char(1) CONSTRAINT user_type_type_type CHECK (VALUE IN ('S', 'I'));
CREATE DOMAIN system_user_type_type  char(1) CONSTRAINT system_user_type_type_type CHECK (VALUE IN ('O', 'D'));
CREATE DOMAIN license_id_type varchar(30);
CREATE DOMAIN id_type bigint;
CREATE DOMAIN otp_type varchar(6);
CREATE DOMAIN description_type varchar(256);
CREATE DOMAIN amount_type numeric;
CREATE DOMAIN notes_type varchar(256);
CREATE DOMAIN quantity_type numeric;

CREATE DOMAIN tax_identity_type_type varchar(5) CONSTRAINT tax_identity_type_type_values CHECK (VALUE IN ('IT', 'IP'));
CREATE DOMAIN tax_identifier_type varchar(20);
CREATE DOMAIN address_id_type varchar(10);

CREATE DOMAIN order_num_type varchar(20);
CREATE DOMAIN item_id_type varchar(20);
CREATE DOMAIN general_string_type varchar(500);
CREATE DOMAIN num_type decimal;
CREATE DOMAIN order_id_type varchar(10);
CREATE DOMAIN msg_type_name_type varchar(30);

CREATE DOMAIN acct_identifier_type varchar(20);
CREATE DOMAIN acct_name_type varchar(100);
CREATE DOMAIN acct_number_type varchar(34);

